### ISSUE TITLE
shortcuts customization

### ISSUE THREAD

**Issue by Muji-k** [mrkwnzl/gridless-grid-foundryvtt#1]
Hi, thanks for creating this module,
the module works fine, but as i run my foundry in a browser through NodeJS instead of the windows program, the shortcuts for the module actions conflict with Mozilla Firefox default shortcuts, so is there a way to change the shortcuts used by the module?

**Comment by mrkwnzl** [comment]
Hey! Thanks, I’m glad you like it. You can change all keyboard commands in the “Configure Controls” settings. Make sure you are updated to the latest version, as I have implemented this in one of the last versions.

Let me know if that is working for you!

**Comment by Muji-k** [comment]
yes its working sorry to have opened an issue when the function is already implemented in default foundry....
i just never had to change a shortcut before....
but I'm glad to have discovered this...
thanks for taking the time to explain this to me....
